yorubaNames = ['Abayomrunkoje', 'Abegunde', 'Abeo', 'Abiade', 'Abidogun', 'Abiodun', 'Abiola',
        'Abioye', 'Adebamgbe', 'Adebiyi', 'Adedayo', 'Ademola', 'Adeniyi', 'Adepero', 'Adesanya', 
        'Adeshola', 'Adesola', 'Adetayo', 'Adetokunbo', 'Adetola', 'Adetope', 'Adetosoye', 'Adisa', 
        'Akin', 'Alake', 'Apara', 'Ayinde', 'Ayodele', 'Ayotomiwa', 'Babasola', 'Babatunji', 'Banjoko', 
        'Bankole', 'Bayode', 'Bayowa', 'Bolade', 'Damola', 'Durojaiye', 'Durosinmi', 'Esupofo', 'Farayioluwola',
        'Fiyinfolu', 'Folarin', 'Folu', 'Gbadebo', 'Idogbe', 'Ifelewa', 'Iles', 'Inioluwa', 'Iranola',
        'Isamotu Olalekan', 'Iseoluwa', 'Iyanu-Oluwa', 'Jesutosin', 'Jimoh', 'Kaseko', 'Mabayoje', 
        'Majekodunmi', 'Mayowa', 'Mobo', 'Mobolaji', 'Modadeola', 'Modurodoluwa', 
        'Modurolorilerioluwa', 'Mofetoluwa', 'Mofihinfoluwa', 'Mofolorunso', 'Naade', 
        'Numilekunoluwa', 'Oba', 'Obafemi', 'Obaloluwa', 'Obasolape', 'Obatotosinloluwa', 'Odunayo', 
        'Ogooluwa', 'Olabamiji', 'Olabisi', 'Olabode', 'Oladayo', 'Olamilekan', 'Oson', 'Pamilekunayo', 
        'Remilekun', 'Rereloluwa', 'Ropo', 'Sangodele', 'Sareola', 'Seriki', 'Seye', 'Shakale', 'Shoyebi', 
        'Shijuade', 'Sinmiloluwa', 'Sunkanmi', 'Sunmoluwa', 'Tadenikawo', 'Tanimola', 'Tantoluwa', 'Tayo', 
        'Teleayo', 'Teleola', 'Temidayo', 'Temiloluwa', 'Temitope', 'Teniayo', 'Tifeoluwa', 'Tiwalade', 'Tiwatope', 
        'Tolulola', 'Tolulope', 'Toluwalase', 'Toluwalogo', 'Toluwalope', 'Toluwanimi', 'Tomori', 'Tosin', 'Yele', 
        'Abebi', 'Abidemi', 'Abiona', 'Adankwo', 'Adaoma', 'Adaora', 'Adefolake', 'Aderiyike', 'Adesina', 'Adunni', 
        'Aega', 'Aina', 'Amoke', 'Atinuke', 'Ayobami', 'Ayokunumi', 'Ayomisioluwakonitan', 'Ayoola', 'Ayotola', 
        'Ayotoluwafunmi', 'Ayotundun', 'Ayowonuola', 'Ayowunmi', 'Bandele', 'Bere', 'Bidemi', 'Bimpe', 'Bisi', 
        'Bmidele', 'Bodunde', 'Bolanle', 'Bolatito', 'Boluwaji', 'Boluwatife', 'Bosede', 'Bunmi', 'Busayo', 
        'Dideoluwakusidede', 'Diekololaoluwa', 'Diekololaoluwalayemi', 'Doyinsola', 'Ebunoluwa', 'Emilohi', 
        'Eniiyi', 'Enitan', 'Eriifeoluwa', 'Eromidola', 'Eyitope', 'Fadekunmi', 'Fehintola', 'Feyisayo', 
        'Feyisetan', 'Feyisola', 'Fiayosemi', 'Fibikemi', 'Fisayo', 'Folade', 'Folake', 'Folaoluwashade', 
        'Folasade', 'Folusho', 'Fowoke', 'Foyinsola', 'Funmilayo', 'Fyiynfoluwa', 'Gbemisola', 'Gbohunmi', 
        'Gbolahun', 'Gboyega', 'Ibidolapo', 'Ibidun', 'Ibilola', 'Ibironke', 'Ibukun', 'Ibukunade', 'Ibukunoluwa', 
        'Idowu', 'Ifedayo', 'Ifede', 'Ifedolaoluwa', 'Ifedolapo', 'Ifejesukristi', 'Ifelayo', 'Ifeoluwadolapo', 
        'Ifesowapo', 'Ifetundun', 'Ifeya', 'Ikeoluwa', 'Ileara', 'Ilerioluwa', 'Iretomiwa', 'Isoken', 'Iyawa', 
        'Jadesola', 'Jadesolaoluwa', 'Jaiyeola', 'Jesulayotimoni', 'Jibola', 'Jolasun', 'Kayin', 'Kehinde', 'Keyshia', 
        'Kikelomo', 'Kinfeosioluwa', 'Kokumo', 'Kolapo', 'Kolawole', 'Korede', 'Lanre', 'Latorunwa', 'Lolade', 
        'Mofoluwakemi', 'Monife', 'Olamide', 'Oluchi', 'Oluwabusola', 'Oluwafunbi', 'Omolade', 'Omorinsola', 
        'Orisa', 'Oyinlola', 'Ronke', 'Shola', 'Tambara', 'Tiaraoluwa', 'Timilehin', 'Titilayo', 'Toluwalashe', 
        'Tujuka', 'Yejide', 'Zoputan', 'Ajayi', 'Ayomide', 'Ayotunde', 'Ige', 'Jaiyesimi', 'Modupeore', 
        'Monjolaoluwa', 'Morenikeji', 'Niyilolawa', 'Olajuwan', 'Olayinka', 'Olorunyomi', 'Olumoroti', 'Olusola', 
        'Oluwagbenga', 'Oluwatoke', 'Tejumola', 'Tiwa', 'Tokunbo']


